"use client";

import Link from "next/link";
import { motion } from "motion/react";
import { ArrowRight, Carrot, CheckCircle2, ChevronRight, CircleAlert, Clock3, CookingPot, Dices, Leaf, PackageOpen, Sparkles } from "lucide-react";
import { DAY_NAMES, MEAL_CATALOG } from "@/constants/kitchen";
import { useKitchen } from "@/features/kitchen/kitchen-provider";
import { calculateMealMatch } from "@/features/meals/matching";
import { daysUntil, getWeekDates, toIsoDate } from "@/lib/date/week";
import { formatQuantity } from "@/lib/units";

export function DashboardView() {
  const kitchen = useKitchen();
  const dates = getWeekDates();
  const today = toIsoDate(new Date());
  const activeIngredients = kitchen.ingredients.filter((item) => item.quantity > 0);
  const expiring = activeIngredients.filter((item) => { const days = daysUntil(item.expirationDate); return days !== null && days <= 3; }).sort((a, b) => (a.expirationDate ?? "").localeCompare(b.expirationDate ?? ""));
  const todayPlan = kitchen.plannedMeals.find((item) => item.date === today);
  const bestMeal = todayPlan ? kitchen.meals.find((meal) => meal.id === todayPlan.mealId) : [...MEAL_CATALOG].sort((a, b) => calculateMealMatch(b, activeIngredients).score - calculateMealMatch(a, activeIngredients).score)[0];
  const bestMatch = bestMeal ? calculateMealMatch(bestMeal, activeIngredients) : null;
  const headingDate = new Intl.DateTimeFormat("en-US", { weekday: "long", day: "numeric", month: "long" }).format(new Date()).toUpperCase();
  return <motion.div initial={false} animate={{ opacity: 1, y: 0 }}>
    <header className="mb-7 flex items-start justify-between gap-4"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[.18em] text-accent">{headingDate}</p><h1 className="text-3xl font-bold tracking-[-.04em] sm:text-4xl">คืนนี้กินอะไรดี <span aria-hidden="true">👀</span></h1><p className="mt-2 text-sm text-muted">ของที่มีอยู่ ไปได้อีกหลายมื้อเลย</p></div><div className="hidden items-center gap-2 rounded-full bg-[var(--card)] px-4 py-2 text-xs font-semibold shadow-sm sm:flex"><span className="size-2 rounded-full bg-success" /> ครัวพร้อมใช้งาน</div></header>
    <section className="grid gap-5 xl:grid-cols-[1.4fr_.75fr]">
      <div className="relative min-h-[330px] overflow-hidden rounded-[34px] bg-[var(--sidebar)] p-6 text-[var(--sidebar-fg)] sm:p-9"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-[var(--accent)] opacity-15 blur-2xl" /><div className="absolute bottom-[-45%] right-[12%] size-72 rounded-full bg-white/5" /><div className="relative z-10 max-w-lg"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-[11px] font-semibold text-white/75"><Sparkles size={13} className="text-[var(--accent)]" /> วางแผนให้จากของที่มี</span><h2 className="mt-5 text-balance text-3xl font-bold leading-tight tracking-[-.04em] sm:text-[2.6rem]">ปล่อยให้ครัว<br /><span className="text-[var(--accent)]">เลือกมื้ออร่อย</span>ให้คุณ</h2><p className="mt-4 max-w-sm text-sm leading-6 text-white/55">สุ่มครบ 7 วัน เน้นวัตถุดิบใกล้หมดอายุ และไม่วนเมนูเดิมจนน่าเบื่อ</p><Link href="/planner" className="mt-7 inline-flex h-12 items-center gap-3 rounded-2xl bg-[var(--accent)] px-5 text-sm font-bold text-white shadow-lg shadow-black/20 transition-transform hover:-translate-y-0.5"><Dices size={18} /> สุ่มเมนูอาทิตย์นี้ <ArrowRight size={16} /></Link></div><div aria-hidden="true" className="absolute -right-6 bottom-0 hidden h-full w-[42%] sm:block"><div className="absolute left-1/2 top-1/2 size-52 -translate-x-1/2 -translate-y-1/2 rounded-full border-[14px] border-white/80 bg-[#f2d085] shadow-2xl shadow-black/30"><div className="absolute inset-5 rounded-full bg-[#9c4c35]"><span className="absolute left-[25%] top-[25%] size-8 rounded-full bg-[#568257]" /><span className="absolute right-[20%] top-[35%] size-5 rounded-full bg-[#e28f31]" /><span className="absolute bottom-[20%] left-[45%] h-10 w-4 rotate-45 rounded-full bg-[#6b9a53]" /></div></div><Leaf className="absolute left-[10%] top-[19%] rotate-[-25deg] text-[#8fb27d]" size={45} /><div className="absolute bottom-[18%] right-[4%] size-9 rotate-12 rounded-full bg-[#eaa444]" /></div></div>
      <div className="grid grid-cols-2 gap-4 xl:grid-cols-1"><div className="surface-card flex min-h-36 flex-col justify-between rounded-[28px] p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-2xl bg-[var(--secondary)] text-primary"><Carrot size={20} /></span><span className="text-[10px] font-bold tracking-wider text-muted">PANTRY</span></div><div><p className="text-3xl font-bold tracking-tight">{activeIngredients.length}</p><p className="text-xs text-muted">วัตถุดิบพร้อมใช้</p></div></div><div className="surface-card flex min-h-36 flex-col justify-between rounded-[28px] p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-2xl bg-[var(--accent-soft)] text-accent"><CircleAlert size={20} /></span><span className="text-[10px] font-bold tracking-wider text-muted">USE SOON</span></div><div><p className="text-3xl font-bold tracking-tight">{expiring.length}</p><p className="text-xs text-muted">รายการควรรีบใช้</p></div></div></div>
    </section>
    <section className="mt-7 grid gap-7 xl:grid-cols-[1fr_1.6fr]">
      <div><SectionTitle eyebrow="COOK NEXT" title="มื้อต่อไปของคุณ" href="/planner" action="ดูแผน" />{bestMeal && bestMatch ? <Link href={todayPlan ? `/planner/${today}` : "/planner"} className="surface-card group flex min-h-52 flex-col justify-between overflow-hidden rounded-[28px] p-5 transition-transform hover:-translate-y-1"><div className="flex items-start justify-between"><div className="max-w-[70%]"><span className="inline-flex items-center gap-1 rounded-full bg-emerald-500/10 px-2.5 py-1 text-[10px] font-bold text-success"><CheckCircle2 size={12} /> พร้อมทำ {bestMatch.score}%</span><h3 className="mt-4 text-2xl font-bold tracking-tight">{bestMeal.name}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted">{bestMeal.description}</p></div><span className="grid size-14 place-items-center rounded-[20px] bg-[var(--accent-soft)] text-accent"><CookingPot size={27} /></span></div><div className="mt-5 flex items-center gap-4 border-t border-[var(--border)] pt-4 text-xs text-muted"><span className="flex items-center gap-1.5"><Clock3 size={14} /> {bestMeal.cookingTimeMinutes} นาที</span><span className="ml-auto font-bold text-primary">ดูรายละเอียด <ArrowRight className="inline" size={14} /></span></div></Link> : <div className="soft-card grid min-h-52 place-items-center rounded-[28px] text-center text-sm text-muted"><div><PackageOpen className="mx-auto mb-3" /><p>เพิ่มวัตถุดิบก่อน แล้วเราจะหาเมนูให้</p></div></div>}</div>
      <div><SectionTitle eyebrow="THIS WEEK" title="แผนมื้ออาหาร" href="/planner" action="จัดแผน" /><div className="surface-card overflow-x-auto rounded-[28px]"><div className="grid min-w-[630px] grid-cols-7 divide-x divide-[var(--border)]">{dates.map((date, index) => { const plan = kitchen.plannedMeals.find((item) => item.date === date); const meal = kitchen.meals.find((item) => item.id === plan?.mealId); return <Link href={meal ? `/planner/${date}` : "/planner"} key={date} className={`group min-h-52 p-3 text-center transition-colors hover:bg-[var(--muted-soft)] ${date === today ? "bg-[var(--secondary)]" : ""}`}><p className="text-[9px] font-bold tracking-wider text-muted">{DAY_NAMES[index].english.slice(0, 3)}</p><p className={`mx-auto mt-2 grid size-8 place-items-center rounded-full text-sm font-bold ${date === today ? "bg-primary text-primary-foreground" : ""}`}>{Number(date.slice(-2))}</p><div className="mx-auto my-4 grid size-11 place-items-center rounded-[18px] bg-[var(--accent-soft)] text-accent"><CookingPot size={19} /></div><p className="line-clamp-2 text-xs font-bold leading-5">{meal?.name ?? "ยังว่าง"}</p>{meal && <p className="mt-1 text-[10px] text-success">{plan?.matchScore}%</p>}</Link>; })}</div></div></div>
    </section>
    {expiring.length > 0 && <section className="mt-7"><SectionTitle eyebrow="DON'T WASTE" title="ใช้ของพวกนี้ก่อน" href="/ingredients" action="ดูทั้งหมด" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{expiring.slice(0, 3).map((ingredient) => { const remaining = daysUntil(ingredient.expirationDate); return <Link href="/ingredients" key={ingredient.id} className="soft-card flex items-center gap-4 rounded-[22px] p-4 transition-transform hover:-translate-y-0.5"><span className="grid size-11 place-items-center rounded-[17px] bg-[var(--card)] text-primary"><Leaf size={20} /></span><div className="min-w-0"><p className="truncate text-sm font-bold">{ingredient.name}</p><p className="text-xs text-muted">เหลือ {formatQuantity(ingredient.quantity, ingredient.unit)}</p></div><span className="ml-auto shrink-0 rounded-full bg-amber-500/10 px-2.5 py-1 text-[10px] font-bold text-warning">{remaining !== null && remaining < 0 ? "เลยกำหนด" : remaining === 0 ? "วันนี้" : `${remaining} วัน`}</span></Link>; })}</div></section>}
  </motion.div>;
}

function SectionTitle({ eyebrow, title, href, action }: { eyebrow: string; title: string; href: string; action: string }) {
  return <div className="mb-4 flex items-end justify-between"><div><p className="text-[10px] font-bold tracking-[.16em] text-accent">{eyebrow}</p><h2 className="mt-1 text-xl font-bold">{title}</h2></div><Link href={href} className="text-xs font-semibold text-primary">{action} <ChevronRight className="inline" size={14} /></Link></div>;
}
