"use client";

import { motion } from "motion/react";
import { Check, Cloud, Database, Palette, RefreshCw, SlidersHorizontal, Trash2 } from "lucide-react";
import { useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { SecondaryButton } from "@/components/ui/primitives";
import { useKitchen } from "@/features/kitchen/kitchen-provider";
import type { ThemeName } from "@/types/kitchen";

const themes: Array<{ id: ThemeName; name: string; description: string; colors: string[] }> = [
  { id: "minimal", name: "Minimal Light", description: "ขาวสะอาด เรียบคม", colors: ["#f6f6f4", "#1b1b1b", "#ff684d"] },
  { id: "midnight", name: "Midnight", description: "ดำสนิท สบายตา", colors: ["#101210", "#d9ee91", "#ff795b"] },
  { id: "matcha", name: "Matcha", description: "ครีมและเขียวละมุน", colors: ["#f4f2e8", "#48664c", "#ed704c"] },
  { id: "sakura", name: "Sakura", description: "ขาวชมพูอ่อน", colors: ["#fbf3f4", "#a85168", "#df795e"] },
  { id: "ocean", name: "Ocean", description: "ฟ้าเย็นและไซแอน", colors: ["#eef6f7", "#176b78", "#ed7652"] },
  { id: "mango", name: "Mango", description: "ครีมเหลืองอบอุ่น", colors: ["#fbf4df", "#a65a1c", "#e4931a"] },
  { id: "grape", name: "Grape", description: "ม่วงเข้มละมุน", colors: ["#17131e", "#c7a0ff", "#ff8065"] },
  { id: "night-market", name: "Thai Night Market", description: "ถ่านดำกับไฟนีออน", colors: ["#131514", "#f3bd44", "#ff664b"] },
];

export function SettingsView() {
  const kitchen = useKitchen();
  const [confirmClear, setConfirmClear] = useState(false);
  return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><PageHeader eyebrow="MAKE IT YOURS" title="ตั้งค่าครัวของคุณ" description="เลือกบรรยากาศที่ใช่ ข้อมูลทุกอย่างยังอยู่เหมือนเดิมเมื่อเปลี่ยนธีม" />
    <div className="grid gap-6 xl:grid-cols-[1.5fr_.75fr]"><section className="surface-card rounded-[30px] p-5 sm:p-7"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-[17px] bg-[var(--secondary)] text-primary"><Palette size={21} /></span><div><h2 className="font-bold">โทนสี</h2><p className="text-xs text-muted">8 บรรยากาศ เปลี่ยนได้ทันที</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{themes.map((theme) => { const active = kitchen.theme.theme === theme.id; return <button key={theme.id} onClick={() => kitchen.updateTheme({ theme: theme.id })} className={`relative flex items-center gap-4 rounded-[20px] border p-4 text-left transition-all hover:-translate-y-0.5 ${active ? "border-[var(--primary)] bg-[var(--secondary)]" : "border-[var(--border)] hover:bg-[var(--muted-soft)]"}`}><span className="flex -space-x-2">{theme.colors.map((color) => <i key={color} className="size-8 rounded-full border-2 border-[var(--card)]" style={{ background: color }} />)}</span><span><strong className="block text-sm">{theme.name}</strong><small className="text-[10px] text-muted">{theme.description}</small></span>{active && <span className="absolute right-3 top-3 grid size-5 place-items-center rounded-full bg-primary text-primary-foreground"><Check size={12} /></span>}</button>; })}</div>
      <div className="mt-7 border-t border-[var(--border)] pt-6"><div className="mb-4 flex items-center gap-2"><SlidersHorizontal size={18} className="text-primary" /><h3 className="text-sm font-bold">ปรับเองเพิ่มเติม</h3></div><div className="grid gap-4 sm:grid-cols-2"><ColorInput label="สีหลัก" value={kitchen.theme.customPrimary} onChange={(value) => kitchen.updateTheme({ customPrimary: value, theme: "custom" })} /><ColorInput label="สีแต้ม" value={kitchen.theme.customAccent} onChange={(value) => kitchen.updateTheme({ customAccent: value, theme: "custom" })} /><SelectSetting label="พื้นหลัง" value={kitchen.theme.backgroundStyle} onChange={(value) => kitchen.updateTheme({ backgroundStyle: value as "solid" | "soft" | "ambient" })} options={[{ value: "solid", label: "สีเรียบ" }, { value: "soft", label: "แสงนุ่ม" }, { value: "ambient", label: "แสงบรรยากาศ" }]} /><SelectSetting label="สไตล์การ์ด" value={kitchen.theme.cardStyle} onChange={(value) => kitchen.updateTheme({ cardStyle: value as "soft" | "flat" | "glass" })} options={[{ value: "soft", label: "นุ่มมีเงา" }, { value: "flat", label: "เรียบมีเส้น" }, { value: "glass", label: "โปร่งเบา" }]} /></div></div>
    </section>
    <div className="space-y-5"><section className="surface-card rounded-[28px] p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[15px] bg-emerald-500/10 text-success"><Database size={18} /></span><div><h2 className="text-sm font-bold">การเก็บข้อมูล</h2><p className="text-[10px] text-muted">{kitchen.cloudStatus === "local" ? "บันทึกบนเครื่องนี้" : kitchen.cloudStatus === "synced" ? "เชื่อม Supabase แล้ว" : kitchen.cloudStatus === "syncing" ? "กำลังซิงก์ข้อมูล" : "ใช้ข้อมูลในเครื่องชั่วคราว"}</p></div></div><p className="mt-4 text-xs leading-6 text-muted">ข้อมูลครัวจะบันทึกในเบราว์เซอร์เสมอ และซิงก์ผ่าน server-only Supabase boundary อัตโนมัติเมื่อกำหนด environment variables ครบ</p><div className="mt-4 flex items-center gap-2 rounded-2xl bg-[var(--muted-soft)] p-3 text-[11px] font-semibold"><Cloud size={15} className={kitchen.cloudStatus === "synced" ? "text-success" : "text-muted"} /> {kitchen.cloudStatus === "local" ? "Local-first · พร้อมเชื่อม Cloud" : kitchen.cloudStatus === "synced" ? "Cloud sync ล่าสุดสำเร็จ" : kitchen.cloudStatus === "syncing" ? "กำลังส่งข้อมูลขึ้น Cloud..." : "Cloud ติดต่อไม่ได้ · ข้อมูลยังอยู่ในเครื่อง"}</div></section>
      <section className="surface-card rounded-[28px] p-5"><h2 className="text-sm font-bold">ข้อมูลตัวอย่าง</h2><p className="mt-1 text-xs leading-5 text-muted">เรียกชุดวัตถุดิบเริ่มต้นกลับมา หรือล้างครัวเพื่อเริ่มจากศูนย์</p><div className="mt-4 grid gap-2"><SecondaryButton onClick={kitchen.resetDemo} className="w-full"><RefreshCw size={15} /> เรียกข้อมูลตัวอย่างกลับมา</SecondaryButton>{confirmClear ? <div className="rounded-2xl bg-red-500/10 p-3"><p className="mb-3 text-center text-xs font-semibold text-danger">ล้างวัตถุดิบ แผน และประวัติทั้งหมด?</p><div className="grid grid-cols-2 gap-2"><button onClick={() => setConfirmClear(false)} className="rounded-xl py-2 text-xs font-semibold text-muted">ยกเลิก</button><button onClick={() => { kitchen.clearKitchen(); setConfirmClear(false); }} className="rounded-xl bg-danger py-2 text-xs font-bold text-white">ล้างทั้งหมด</button></div></div> : <button onClick={() => setConfirmClear(true)} className="flex h-11 items-center justify-center gap-2 rounded-2xl text-xs font-semibold text-danger hover:bg-red-500/10"><Trash2 size={15} /> ล้างข้อมูลครัว</button>}</div></section>
    </div></div>
  </motion.div>;
}

function ColorInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs font-semibold">{label}<span className="mt-2 flex h-12 items-center gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface)] px-3"><input type="color" value={value} onChange={(event) => onChange(event.target.value)} className="size-7 overflow-hidden rounded-full border-0 bg-transparent" /><span className="text-xs uppercase text-muted">{value}</span></span></label>; }
function SelectSetting({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }> }) { return <label className="text-xs font-semibold">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-12 w-full rounded-2xl border border-[var(--border)] bg-[var(--surface)] px-3 text-xs outline-none">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
