export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      ingredients: { Row: { id: string; name: string; normalized_name: string; category: string; quantity: number; normalized_quantity: number; unit: string; normalized_unit: string; purchase_date: string; expiration_date: string | null; notes: string | null; created_at: string; updated_at: string }; Insert: { id?: string; name: string; normalized_name: string; category: string; quantity: number; normalized_quantity: number; unit: string; normalized_unit: string; purchase_date: string; expiration_date?: string | null; notes?: string | null; created_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["ingredients"]["Insert"]>; Relationships: [] };
      meals: { Row: { id: string; name: string; description: string; cuisine: string; meal_type: string; difficulty: string; cooking_time_minutes: number; is_favorite: boolean; source: string; tags: string[]; image_tone: string; created_at: string; updated_at: string }; Insert: { id?: string; name: string; description: string; cuisine: string; meal_type: string; difficulty: string; cooking_time_minutes: number; is_favorite?: boolean; source: string; tags?: string[]; image_tone?: string; created_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["meals"]["Insert"]>; Relationships: [] };
      meal_ingredients: { Row: { id: string; meal_id: string; ingredient_name: string; normalized_name: string; quantity: number; normalized_quantity: number; unit: string; normalized_unit: string; is_optional: boolean; created_at: string }; Insert: { id?: string; meal_id: string; ingredient_name: string; normalized_name: string; quantity: number; normalized_quantity: number; unit: string; normalized_unit: string; is_optional?: boolean; created_at?: string }; Update: Partial<Database["public"]["Tables"]["meal_ingredients"]["Insert"]>; Relationships: [] };
      meal_steps: { Row: { id: string; meal_id: string; step_number: number; instruction: string }; Insert: { id?: string; meal_id: string; step_number: number; instruction: string }; Update: Partial<Database["public"]["Tables"]["meal_steps"]["Insert"]>; Relationships: [] };
      weekly_plans: { Row: { id: string; week_start: string; meals_per_day: number; created_at: string; updated_at: string }; Insert: { id?: string; week_start: string; meals_per_day: number; created_at?: string; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["weekly_plans"]["Insert"]>; Relationships: [] };
      planned_meals: { Row: { id: string; weekly_plan_id: string; date: string; meal_slot: number; meal_id: string; is_locked: boolean; status: string; match_score: number; created_at: string }; Insert: { id?: string; weekly_plan_id: string; date: string; meal_slot: number; meal_id: string; is_locked?: boolean; status?: string; match_score?: number; created_at?: string }; Update: Partial<Database["public"]["Tables"]["planned_meals"]["Insert"]>; Relationships: [] };
      meal_history: { Row: { id: string; meal_id: string; cooked_at: string; ingredients_used: Json; created_at: string }; Insert: { id?: string; meal_id: string; cooked_at?: string; ingredients_used?: Json; created_at?: string }; Update: Partial<Database["public"]["Tables"]["meal_history"]["Insert"]>; Relationships: [] };
      ingredient_transactions: { Row: { id: string; ingredient_id: string | null; ingredient_name: string; type: string; quantity: number; unit: string; reference: string | null; created_at: string }; Insert: { id?: string; ingredient_id?: string | null; ingredient_name: string; type: string; quantity: number; unit: string; reference?: string | null; created_at?: string }; Update: Partial<Database["public"]["Tables"]["ingredient_transactions"]["Insert"]>; Relationships: [] };
      app_preferences: { Row: { id: string; meals_per_day: number; theme: Json; updated_at: string }; Insert: { id?: string; meals_per_day?: number; theme?: Json; updated_at?: string }; Update: Partial<Database["public"]["Tables"]["app_preferences"]["Insert"]>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: { consume_planned_meal: { Args: { target_planned_meal_id: string }; Returns: Json } };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
